vuejs-translations/docs-uk

- .vitepress/theme/styles/index.css
> Виправлено #12

- .vitepress/theme/styles/index.css
#12
@vue/theme перекриває мої стилі, тому...
додати !important
> Повністю виправлено #12

- .vitepress/config.ts
- src/translations/index.md
> Сихронізація з апстрімом

- src/about/faq.md
- src/about/team/members-partner.json
- src/api/component-instance.md
- src/api/options-state.md
- src/api/reactivity-core.md
- src/guide/best-practices/performance.md
- src/guide/extras/composition-api-faq.md
- src/guide/extras/reactivity-in-depth.md
- src/guide/scaling-up/testing.md
- src/partners/partners.json
> Синзронізація з upstream

- src/guide/typescript/options-api.md
Hi there
Please Check the translation
> first attempt

- src/translations/index.md
> update translation page: add link to source, add Ukrainian wip entry

- .vitepress/config.ts
> Виправлено посилання "Редагувати цю сторінку на Github" на новий репозиторій

- src/public/_redirects
> feat: Permanent redirect to official site from the old one

- src/public/_redirects
> feat: Permanent redirect to official site from the old one - attempt 2

- .vitepress/theme/components/Banner.vue
> add padding to support Ukraine banner

- src/api/utility-types.md
- src/guide/scaling-up/testing.md
> Синхронізація з upstream

- src/api/application.md
> Application

- .vitepress/config.ts
> Перекладено незначні елементи інтерфейсу

- src/public/glossary.json
Та забрано дефіс зі слова "односторінковий"
> Виправлено "додаток" на "застосунок"

- .github/pull_request_template.md
> Виправлено неправильний синтаксис

- .vitepress/config.ts
- package.json
- pnpm-lock.yaml
> Синхронізація

- .vitepress/theme/components/SiteMap.vue
- src/about/releases.md
- src/about/team/Member.ts
- src/about/team/members-core.json
- src/api/ssr.md
- src/ecosystem/themes/ThemePage.vue
- src/ecosystem/themes/themes.json
- src/guide/best-practices/accessibility.md
- src/guide/best-practices/performance.md
- src/guide/components/v-model.md
- src/guide/essentials/class-and-style.md
- src/guide/essentials/forms.md
- src/guide/essentials/reactivity-fundamentals.md
- src/guide/extras/composition-api-faq.md
- src/guide/introduction.md
- src/guide/quick-start.md
- src/guide/reusability/composables.md
- src/guide/scaling-up/tooling.md
- src/guide/typescript/composition-api.md
- src/guide/typescript/options-api.md
- src/guide/typescript/overview.md
- src/partners/components/PartnerLanding.vue
- src/partners/components/PartnerList.vue
- src/partners/partners.json
- src/sponsor/index.md
- src/style-guide/rules-strongly-recommended.md
- src/translations/index.md
> Отримання змін з upstream

- README.md
> Змінено README

- README.md
> Оновлено посилання на репозиторій

- src/tutorial/src/step-8/App/composition.js
- src/tutorial/src/step-8/App/options.js
- src/tutorial/src/step-8/App/template.html
- src/tutorial/src/step-8/_hint/App/composition.js
- src/tutorial/src/step-8/_hint/App/options.js
- src/tutorial/src/step-8/_hint/App/template.html
- src/tutorial/src/step-8/description.md
> Переклад: Посібник, крок 8

- src/tutorial/src/step-9/App/template.html
- src/tutorial/src/step-9/_hint/App/composition.js
- src/tutorial/src/step-9/_hint/App/options.js
- src/tutorial/src/step-9/description.md
> Переклад: Посібник, крок 9

- src/tutorial/src/step-10/App/template.html
- src/tutorial/src/step-10/description.md
> Переклад: Посібник, крок 10

- src/guide/extras/rendering-mechanism.md
> translation: guide/extras/rendering-mechanism

- src/guide/extras/composition-api-faq.md
> translation: guide/extras/composition-api-faq

- src/guide/extras/reactivity-transform.md
> translation: guide/extras/reactivity-transform

- src/api/render-function.md
> translation: api/render-function

- src/api/ssr.md
> translation: api/ssr

- src/api/utility-types.md
> translation: api/utility-types

- src/api/custom-renderer.md
> translation: custom renderer

- src/tutorial/src/step-14/App/composition.js
- src/tutorial/src/step-14/App/options.js
- src/tutorial/src/step-14/ChildComp/template.html
- src/tutorial/src/step-14/_hint/App/template.html
- src/tutorial/src/step-14/description.md
> Переклад: Посібник, крок 14

- src/guide/reusability/plugins.md
> translation: guide/reusability/plugins

- src/tutorial/src/step-15/App/template.html
- src/tutorial/src/step-15/description.md
> Переклад: Посібник, крок 15

- .vitepress/config.ts
- src/translations/index.md
> feat: Update translation links

- .vitepress/theme/index.ts
> Видалено банер

- src/guide/typescript/composition-api.md
> Sync upstream

- .vitepress/config.ts
> Видалено дублікат французького перекладу

- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
- .vitepress/theme/index.ts
- src/guide/essentials/event-handling.md
#	.vitepress/theme/components/Banner.vue
#	src/guide/essentials/event-handling.md- [ ] Я ознайомлений(а) з [Правилами спільноти](https://github.com/vuejs-translations/docs-uk/wiki/Правила-спільноти) та зобов'язуюсь їх дотримуватись.
> Fix scroll performance link (vuejs#2513)

- .vitepress/config.ts
> fix: Pinia link

- .vitepress/config.ts
> Added space between words

- src/guide/introduction.md
- FIXED: if follow the link that should lead to Options API example - it shows Composition API example.
- FIXED: Code inside examples wasn't fully translated.
> Code examples translated + correct links to Vue SFC Playground provided

- src/guide/scaling-up/ssr.md
> Fixed SSR title typo
